In [39]:
from narwhals.selectors import categorical
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: C:\Users\HP\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split,KFold,learning_curve
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from scipy.stats import entropy
import os

%matplotlib widget
plt.style.use("E:\\BongoDev\\Regression Analysis\\deeplearning.mplstyle")

In [41]:
"""
Machine Learning Algorithm:
1. Supervised learning: data contains labels i.e Regression,Classification
2. Unsupervised Learning: data does not contain lables i.e. Clustering
3. Reinforcement Learning : Machine learns through penalty/reward/feedback systems
    i.e. ChatGPT
    1. Train a Text to Text generation model
    2. Task Specific fine tuning the model using reinforcement learning
"""

ROOT_DIR="E:\\BongoDev\\Regression Analysis"
DATA_DIR=os.path.join(ROOT_DIR,"Data")
Dataset_path=os.path.join(DATA_DIR,'housing.csv')

In [42]:
housing_dataset=pd.read_csv(Dataset_path)
housing_dataset.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [43]:
housing_dataset.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [44]:
housing_dataset=housing_dataset[['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus','price']]

In [45]:
housing_dataset.head()

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price
0,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,13300000
1,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,12250000
2,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,12250000
3,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,12215000
4,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,11410000

In [46]:
housing_dataset.isnull().sum()

area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
price               0
dtype: int64

In [47]:
housing_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   area              545 non-null    int64
 1   bedrooms          545 non-null    int64
 2   bathrooms         545 non-null    int64
 3   stories           545 non-null    int64
 4   mainroad          545 non-null    str
 5   guestroom         545 non-null    str
 6   basement          545 non-null    str
 7   hotwaterheating   545 non-null    str
 8   airconditioning   545 non-null    str
 9   parking           545 non-null    int64
 10  prefarea          545 non-null    str
 11  furnishingstatus  545 non-null    str
 12  price             545 non-null    int64
dtypes: int64(6), str(7)
memory usage: 69.2 KB

In [48]:
"""
Normalization:
1. Min-Max Normalization   ( 0 -1)
       xmin=20
       xmax=40
       range=20
       if x=30 then x_norm=(x-xmin)/range  =  (30-20)/20=0.5

2. Standardization/ Z-score  (Mean=0, Std=1,Zero Mean,Unit Variance)  ( DEFAULT)
       mean=20
       std=30
       if =30 then z-score=(x-mean)/std=(30-20)/30=0.33

       for example we have 10 images each 3 X 3
       average image=[_ _ _
                      _ _ _
                      _ _ _
                     ]
       For a single image:
              1. remove average image from that image
              2. normalize by diving the std
"""
# Select columns

numerical_cols=housing_dataset.select_dtypes(include='number').columns.drop('price')
categorical_cols=housing_dataset.select_dtypes(include=['object','str']).columns
numerical_cols

Index(['area', 'bedrooms', 'bathrooms', 'stories', 'parking'], dtype='str')

In [49]:
categorical_cols

Index(['mainroad', 'guestroom', 'basement', 'hotwaterheating',
       'airconditioning', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [50]:
scaler=StandardScaler()

housing_dataset[numerical_cols]=scaler.fit_transform(housing_dataset[numerical_cols])

In [51]:
housing_dataset.head()

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,price
0,1.046726,1.403419,1.421812,1.378217,yes,no,no,no,yes,1.517692,yes,furnished,13300000
1,1.757010,1.403419,5.405809,2.532024,yes,no,no,no,yes,2.679409,no,furnished,12250000
2,2.218232,0.047278,1.421812,0.224410,yes,no,yes,no,no,1.517692,yes,semi-furnished,12250000
3,1.083624,1.403419,1.421812,0.224410,yes,no,yes,no,yes,2.679409,yes,furnished,12215000
4,1.046726,1.403419,-0.570187,0.224410,yes,yes,yes,no,yes,1.517692,no,furnished,11410000