In [3]:
import numpy as np
import pandas as pd

In [2]:
DATASET_PATH="E:\\BongoDev\\Regression Analysis\\Data\\housing.csv"

In [4]:
housing_dataset=pd.read_csv(DATASET_PATH)
housing_dataset.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [7]:
"""
Feature Engineering
"""
housing_dataset=housing_dataset[['area','price']]
housing_dataset.head()

   area     price
0  7420  13300000
1  8960  12250000
2  9960  12250000
3  7500  12215000
4  7420  11410000

In [9]:
# Standardization
mean=housing_dataset.mean()
std=housing_dataset.std()
housing_dataset=(housing_dataset-mean)/std
housing_dataset.head()

       area     price
0  1.045766  4.562174
1  1.755397  4.000809
2  2.216196  4.000809
3  1.082630  3.982096
4  1.045766  3.551716

In [ ]:
"""
ML Algorithm
-Supervised Algorithm
    -Regression
    -Classification
-Unsupervised Algorithm
    -Clustering
-Reinforcement Learning
-Semi-Supervised Learning
""";

In [ ]:
"""
ML Checklist
1. Create a  research proposal (1 page)
2. Identify the research questions ( Specific,Measurable,Relevant questions that are unknown and yet to be solved) and organize
3. For each Research question:
    3.1. Perform Literature Review
    3.2. Comment if the research question is answered  :fully/partially/unanswered
    3.3. Identify Literature Gaps
    3.4. Design an Experiment ( Robust,Reproducible,Rigorous)
    3.5. Result Analysis
""";

In [12]:
"""
Linear Regression
-Single input LR : y_pred=w*x+b
-Multiple input LR:y_pred=w1*x1+w2*x2+.....wn*xn+b

Polynomial Regression  ( Any equation who degree greater than 1)
    y_pred=ax^2+bx^1+cx^0 (degree:2) (a,b,c coefficients)

Why polynomial equation instead of linear equation?
-To recognize non linear pattern
"""

from sklearn.model_selection import train_test_split

X=housing_dataset.drop('price',axis=1).values
y=housing_dataset['price'].values
print(X.shape)
print(y.shape)

X_train_val,X_test,y_train_val,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

(545, 1)
(545,)

In [13]:
X_train,X_val,y_train,y_val=train_test_split(X_train_val,y_train_val,test_size=0.25,random_state=42)

In [14]:
X_train.shape,X_val.shape,X_test.shape

((327, 1), (109, 1), (109, 1))

In [15]:
def model(x,w1,w2,b):
    y_pred=w1 * x**3 + w2 * x**2+b
    return y_pred

In [17]:
"""
Parameter Initialization
"""
np.random.seed(42)
w1=np.random.randint(low=100,high=200)
w2=np.random.randint(low=100,high=200)
b=np.random.randint(low=100,high=200)

print(w1,w2,b)
y_pred=model(X_train,w1,w2,b)
y_pred

151 192 114

array([[ 1.33657690e+02],
       [ 1.44283763e+03],
       [ 1.34868868e+02],
       [ 4.98326767e+02],
       [ 1.52473851e+02],
       [ 1.72792246e+03],
       [ 1.32473565e+02],
       [ 1.48862080e+02],
       [ 1.56089783e+03],
       [ 2.09924738e+02],
       [ 1.53379871e+02],
       [ 1.59239640e+02],
       [ 1.25499368e+02],
       [ 1.14873519e+02],
       [ 5.44795298e+03],
       [ 1.30718924e+02],
       [ 1.56209898e+02],
       [ 1.14220407e+02],
       [ 1.52198677e+02],
       [ 1.55300131e+02],
       [ 1.48260516e+02],
       [ 1.14478210e+02],
       [ 6.13952760e+02],
       [ 1.20924314e+02],
       [ 1.16766368e+02],
       [ 1.18373206e+02],
       [ 1.55601999e+02],
       [ 1.81493953e+02],
       [ 3.17885161e+02],
       [ 1.41126859e+02],
       [ 1.50456084e+02],
       [ 1.53105208e+02],
       [ 1.56599022e+02],
       [ 1.56938786e+02],
       [ 8.11473742e+01],
       [ 1.58341497e+02],
       [ 1.17489095e+02],
       [ 1.33657690e+02],
       [ 9.45565904e+02],
       [ 1.47373808e+02],
       [ 1.33657690e+02],
       [ 3.46913309e+02],
       [ 1.52473851e+02],
       [ 1.51234161e+02],
       [ 1.53379871e+02],
       [ 1.27185819e+02],
       [ 1.42047437e+02],
       [ 5.93604776e+01],
       [ 8.79480476e+02],
       [ 9.98095406e+01],
       [ 8.47746166e+02],
       [-2.01817676e+01],
       [ 2.24548248e+02],
       [ 1.58398767e+02],
       [ 4.68425609e+02],
       [ 1.56650083e+02],
       [ 1.58341497e+02],
       [ 1.27185819e+02],
       [ 1.47869784e+02],
       [ 1.19609235e+02],
       [ 1.36647093e+02],
       [ 9.45565904e+02],
       [ 1.53515611e+02],
       [ 1.19591222e+02],
       [ 2.24749559e+03],
       [ 8.11473742e+01],
       [ 1.83491606e+02],
       [ 1.93542734e+02],
       [ 1.50456084e+02],
       [ 1.59255869e+02],
       [ 2.44643419e+02],
       [ 1.14101514e+02],
       [ 1.59131388e+02],
       [ 1.52473851e+02],
       [ 1.58398767e+02],
       [ 1.39641747e+02],
       [ 2.50227760e+04],
       [ 5.30649915e+02],
       [ 2.55473066e+02],
       [ 1.41863879e+02],
       [ 1.56318074e+02],
       [ 2.56141950e+03],
       [ 3.89454923e+03],
       [ 1.58870430e+02],
       [ 1.59239640e+02],
       [ 3.46913309e+02],
       [ 1.30357399e+02],
       [ 1.44044286e+02],
       [ 1.58630941e+02],
       [ 1.50972765e+02],
       [ 1.59239640e+02],
       [ 1.57187193e+02],
       [ 1.51492484e+02],
       [ 1.14960010e+02],
       [ 1.26844174e+02],
       [ 1.56318074e+02],
       [ 1.39001619e+02],
       [ 1.14873519e+02],
       [ 2.44643419e+02],
       [ 1.27185819e+02],
       [ 1.42632748e+02],
       [ 1.56100401e+02],
       [ 1.43684595e+02],
       [ 1.63397360e+02],
       [ 1.04612670e+04],
       [ 1.05140228e+03],
       [ 2.09924738e+02],
       [ 1.58630941e+02],
       [ 1.41863879e+02],
       [ 1.58630941e+02],
       [ 1.58460338e+02],
       [ 1.45955152e+02],
       [ 1.41428116e+02],
       [ 1.56100401e+02],
       [ 2.34338840e+02],
       [ 1.27185819e+02],
       [ 1.23577258e+02],
       [ 9.45565904e+02],
       [ 1.59522515e+02],
       [ 1.44044286e+02],
       [ 1.45465254e+02],
       [ 1.59675312e+02],
       [ 2.34338840e+02],
       [ 1.90304139e+02],
       [ 1.34402067e+02],
       [ 1.44044286e+02],
       [ 2.44643419e+02],
       [ 1.23891400e+02],
       [ 1.45465254e+02],
       [ 1.59891823e+02],
       [ 1.52240813e+03],
       [ 1.55601999e+02],
       [ 1.35243360e+02],
       [ 1.50456084e+02],
       [ 1.19609235e+02],
       [ 1.59926875e+02],
       [ 1.26505004e+02],
       [ 1.18373206e+02],
       [ 1.99774685e+02],
       [ 1.27185819e+02],
       [ 1.40756832e+02],
       [ 6.23810709e+02],
       [ 1.14015546e+02],
       [ 1.16766368e+02],
       [ 1.30718924e+02],
       [ 1.27185819e+02],
       [ 2.91223228e+02],
       [ 1.47419060e+02],
       [ 7.57643883e+02],
       [ 1.19441106e+02],
       [ 1.45815604e+02],
       [ 1.43828668e+02],
       [ 1.16766368e+02],
       [ 1.37455874e+02],
       [ 1.57392279e+02],
       [ 5.22844602e+02],
       [ 1.18373206e+02],
       [ 7.75061304e+02],
       [ 2.32339957e+02],
       [ 1.56938786e+02],
       [ 2.48029170e+03],
       [ 1.41126859e+02],
       [ 1.59255869e+02],
       [ 1.56530422e+02],
       [ 1.30718924e+02],
       [ 1.59239640e+02],
       [ 2.10092945e+03],
       [ 1.56089783e+03],
       [ 1.52473851e+02],
       [ 1.46853495e+02],
       [ 1.58630941e+02],
       [ 1.99774685e+02],
       [ 1.59311894e+02],
       [ 1.37510034e+03],
       [ 1.56938786e+02],
       [ 1.56100401e+02],
       [ 4.56736905e+02],
       [ 1.34868868e+02],
       [ 3.46913309e+02],
       [ 8.47746166e+02],
       [ 1.23891400e+02],
       [ 1.35243360e+02],
       [ 1.16766368e+02],
       [ 1.44044286e+02],
       [ 1.14930721e+02],
       [ 1.27185819e+02],
       [ 1.59896757e+02],
       [ 1.59311894e+02],
       [ 7.86838950e+02],
       [ 1.63397360e+02],
       [ 6.74959869e+02],
       [ 1.27172410e+02],
       [ 3.30916704e+03],
       [ 1.46578737e+02],
       [ 2.14231171e+04],
       [ 1.99774685e+02],
       [ 1.56938786e+02],
       [ 5.75736940e+02],
       [ 1.53379871e+02],
       [ 1.59255869e+02],
       [ 4.92551993e+02],
       [ 1.49509098e+02],
       [ 1.27185819e+02],
       [ 1.52473851e+02],
       [ 1.59131388e+02],
       [ 1.54086892e+02],
       [ 1.56100401e+02],
       [ 4.96671181e+02],
       [ 1.56318074e+02],
       [ 8.34564778e+01],
       [ 2.32339957e+02],
       [ 1.58870430e+02],
       [ 3.46913309e+02],
       [ 8.58740047e+01],
       [ 1.58630941e+02],
       [ 1.45465254e+02],
       [ 2.91223228e+02],
       [ 1.42047437e+02],
       [ 1.32179140e+02],
       [ 1.58894475e+02],
       [ 8.11473742e+01],
       [ 5.04994461e+02],
       [ 2.47836677e+02],
       [ 1.57734016e+02],
       [ 1.45465254e+02],
       [ 6.23810709e+02],
       [ 1.59255869e+02],
       [ 1.46509813e+02],
       [ 1.15242616e+02],
       [ 3.16329068e+03],
       [ 1.55601999e+02],
       [ 1.52543449e+02],
       [ 2.30676710e+03],
       [ 4.72343936e+01],
       [ 1.27185819e+02],
       [ 1.16766368e+02],
       [ 1.58834076e+02],
       [ 8.11473742e+01],
       [ 1.55601999e+02],
       [ 1.16766368e+02],
       [ 3.95767073e+02],
       [ 1.15377935e+02],
       [ 2.44643419e+02],
       [ 1.17489095e+02],
       [ 1.49159916e+02],
       [ 1.43684595e+02],
       [ 1.56701253e+02],
       [ 1.39641747e+02],
       [ 1.59522515e+02],
       [ 1.19609235e+02],
       [ 8.35293162e+02],
       [ 1.59970126e+02],
       [ 1.51234161e+02],
       [ 1.16326726e+02],
       [ 1.45465254e+02],
       [ 2.20773446e+02],
       [ 1.44743538e+03],
       [ 5.04994461e+02],
       [ 1.56089783e+03],
       [ 4.12422837e+02],
       [ 1.18373206e+02],
       [ 2.20773446e+02],
       [ 1.58630941e+02],
       [ 1.33657690e+02],
       [ 8.11473742e+01],
       [ 5.33480508e+03],
       [ 1.14000012e+02],
       [ 1.15520423e+02],
       [ 1.59311894e+02],
       [ 1.30357399e+02],
       [ 1.55601999e+02],
       [ 1.41428116e+02],
       [ 2.32339957e+02],
       [ 1.57509176e+02],
       [ 1.59034819e+02],
       [ 1.19089586e+02],
       [ 1.59522515e+02],
       [ 1.58341497e+02],
       [ 1.41863879e+02],
       [ 4.23501377e+02],
       [ 1.44044286e+02],
       [ 2.44643419e+02],
       [ 1.42596263e+02],
       [ 2.44643419e+02],
       [ 3.11773717e+03],
       [ 1.55877491e+02],
       [ 1.22902075e+02],
       [ 1.56938786e+02],
       [ 1.14008575e+02],
       [ 1.18373206e+02],
       [ 1.27185819e+02],
       [ 1.41401564e+02],
       [ 1.03102388e+03],
       [ 3.46913309e+02],
       [ 1.46671027e+02],
       [ 1.50794457e+02],
       [ 1.14965855e+02],
       [ 2.09924738e+02],
       [ 1.55601999e+02],
       [ 1.59983249e+02],
       [ 1.56938786e+02],
       [ 1.50765114e+02],
       [ 1.56318074e+02],
       [ 1.52473851e+02],
       [ 1.45465254e+02],
       [ 1.77330511e+02],
       [ 8.11473742e+01],
       [ 1.52473851e+02],
       [ 1.15985786e+02],
       [ 1.98149589e+02],
       [ 1.52473851e+02],
       [ 1.44044286e+02],
       [ 1.52473851e+02],
       [ 1.19609235e+02],
       [ 1.15377935e+02],
       [ 1.34402067e+02],
       [ 4.82413900e+03],
       [ 1.55601999e+02],
       [ 1.58894475e+02],
       [ 1.19609235e+02],
       [ 4.34096509e+02],
       [ 1.56089783e+03],
       [ 1.58489414e+02],
       [ 1.59777647e+02],
       [ 3.54240143e+03],
       [ 1.30718924e+02],
       [ 1.52473851e+02]])

In [18]:
def cost_function(x,y_true,w1,w2,b):
    y_pred=model(x,w1,w2,b)
    mse=np.mean((y_pred-y_true)**2)
    return mse

In [19]:
mse=cost_function(X_train,y_train,w1,w2,b)
print(f"MSE is {mse:0.2f} (Parameters not learned yet)")

MSE is 4294512.99 (Parameters not learned yet)

In [20]:
def compute_gradient(X,y_true,w1,w2,b):
    delta=1e-9

    cost_1=cost_function(X_train,y_train,w1,w2,b)
    cost_2=cost_function(X_train,y_train,w1+delta,w2,b)
    cost_3=cost_function(X_train,y_train,w1,w2+delta,b)
    cost_4=cost_function(X_train,y_train,w1,w2,b+delta)

    dw1=(cost_2-cost_1)/delta
    dw2=(cost_3-cost_1)/delta
    db=(cost_4-cost_1)/delta

    return dw1,dw2,db

In [ ]:
"""
Hyperparameters
-Learning Rate
-Epoch
-Batch Size
-Optimizer
-Learning Rate Scheduler
""";